from flask import Flask

class Bcrypt:
    def __init__(self, app: Flask | None = ...) -> None: ...
    def init_app(self, app: Flask) -> None: ...
    def generate_password_hash(
        self,
        password: str,
        rounds: int | None = ...,
        prefix: bytes | None = ...,
    ) -> bytes: ...
    def check_password_hash(self, pw_hash: str, password: str | bytes) -> bool: ...
