"""BREAKING CHANGES entire new db design need a brand new db

Revision ID: a95cf00be3cd
Revises: c476193bdb85
Create Date: 2026-01-05 16:07:15.040265

"""

import logging
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect, text
from chrono_des_vignes import db

# revision identifiers, used by Alembic.
revision = "a95cf00be3cd"
down_revision = "c476193bdb85"
branch_labels = None
depends_on = None


def check_all_tables_empty():
    inspector = inspect(db.engine)
    table_names = inspector.get_table_names()

    for table_name in table_names:
        if table_name in ("alembic_version", "user"):
            continue  # Skip the excluded table

        # Count rows in the table
        query = text(f"SELECT COUNT(*) FROM {table_name}")
        result = db.session.execute(query).scalar()

        if result and result > 0:
            print(f"Table '{table_name}' is not empty (contains {result} rows).")
            return False

    print("All tables are empty.")
    return True


def upgrade():
    if not check_all_tables_empty():
        logging.error(
            "this is a breaking change please empty all the tables except the alembic_version and user ones"
        )
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parcours_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parcours_id", sa.Integer(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parcours_id"],
            ["parcours.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("parcours", schema=None) as batch_op:
        batch_op.drop_column("creation_date")
        batch_op.drop_column("chronos_list")
        batch_op.drop_column("archived")

    with op.batch_alter_table("stand", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("stand_ibfk_2"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("stand_ibfk_3"), type_="foreignkey")
        batch_op.drop_column("end_stand")
        batch_op.drop_column("start_stand")

    with op.batch_alter_table("trace", schema=None) as batch_op:
        batch_op.add_column(sa.Column("index", sa.Integer(), nullable=False))
        batch_op.drop_column("turn_nb")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password_changed", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    if not check_all_tables_empty():
        logging.error(
            "this is a breaking change please empty all the tables except the alembic_version and user ones"
        )
        return

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("password_changed")

    with op.batch_alter_table("trace", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "turn_nb",
                mysql.INTEGER(display_width=11),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("index")

    with op.batch_alter_table("stand", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "start_stand",
                mysql.INTEGER(display_width=11),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "end_stand",
                mysql.INTEGER(display_width=11),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("stand_ibfk_3"), "parcours", ["end_stand"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("stand_ibfk_2"), "parcours", ["start_stand"], ["id"]
        )

    with op.batch_alter_table("parcours", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "archived",
                mysql.TINYINT(display_width=1),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("chronos_list", mysql.TEXT(), nullable=False))
        batch_op.add_column(
            sa.Column("creation_date", mysql.DATETIME(), nullable=False)
        )

    op.drop_table("parcours_version")
    # ### end Alembic commands ###
