"""adding inscription data

Revision ID: c476193bdb85
Revises: c739e6680052
Create Date: 2025-07-16 16:27:39.143105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c476193bdb85'
down_revision = 'c739e6680052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscription_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'inscription_data', ['data_id'], ['id'])

    with op.batch_alter_table('stand', schema=None) as batch_op:
        batch_op.alter_column('parcours_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('trace', schema=None) as batch_op:
        batch_op.alter_column('parcours_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trace', schema=None) as batch_op:
        batch_op.alter_column('parcours_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('stand', schema=None) as batch_op:
        batch_op.alter_column('parcours_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data_id')

    op.drop_table('inscription_data')
    # ### end Alembic commands ###
